"""changed DB

Revision ID: 1e2727fcd11b
Revises: bb967861d68c
Create Date: 2023-03-25 17:12:55.583721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2727fcd11b'
down_revision = 'bb967861d68c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('answered_questions', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_unique_constraint(None, 'player', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('game', 'answered_questions')
    # ### end Alembic commands ###
