from enum import Enum


class GameStatus(Enum):
    REGISTRATION = "REGISTRATION"
    SETTING_ROUND = "SETTING_ROUND"
    SETTING_QUESTIONS = "SETTING_QUESTIONS"
    STARTED = "STARTED"
    PICKING_QUESTION = "PICKING_QUESTION"
    ANSWERING_QUESTION = "ANSWERING_QUESTION"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"
